services:
  service_example:
    image: service_example
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/root/app
    env_file:
      - .env
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}