services:
  mongodb:
    image: mongo:5.0
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ~/apps/mongo:/data/db

  service_example:
    image: service_example
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - mongodb
    tty: true