[tool.poetry]
name = "fast-api-example"
version = "0.1.0"
description = "Basic FastAPI service"
authors = ["Federico Pacheco <fpacheco@fi.uba.ar>", "Martina Panetta <mpanetta@fi.uba.ar>"]
packages = [
    { include = "app" },
    { include = "app/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.66.0"
uvicorn = "^0.14.0"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
httpx = "^0.23.0"